baseURL: https://rishikeshs.pages.dev/
languageCode: en-us
title: Rishikesh Sreehari
theme: "hugo-PaperMod"
paginate: 5


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Rishikesh Sreehari
  description: "ExampleSite description"
  version: "1.2.0"
  keywords: [Blog, Portfolio, PaperMod]
  #author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: true
  contentDir: "content"
  dataDir: "data"
  books_file: data/books.yaml
  staticDir: "static"
  ignoreErrors: ["error-remote-getjson"]
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  BookShelfDisplayCount: 12
  UtmSource: rishikeshs.com
  CurrentLocation: "Dubai, United Arab Emirates (UAE)"


  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicons/favicon.ico"
    favicon16x16: "favicons/favicon-16x16.png"
    favicon32x32: "favicons/favicon-32x32.png"
    apple_touch_icon: "favicons/apple-touch-icon.png"
    safari_pinned_tab: "favicons/favicon.ico"

  label:
    text: "Rishikesh Sreehari"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi I'm /rishikesh/ \U0001F4AD"
    Content: |

              <p style="margin-bottom: 1em;">This is a nicheless blog, a space where I gather and share my interests, ideas, and document my life. I consider this blog as an <a href="/website-art" style="text-decoration: underline; color: #0066cc;"><strong>evolving art project</strong></a>.</p>

              <p style="margin-bottom: 1em;">I'm currently learning to write better, code and eventually ship products. Eventually I want to create more than I consume.</p>

              <p style="margin-bottom: 1em;">I also write a <a href="https://rishikesh.susbtack.com" style="text-decoration: underline; color: #0066cc;"><strong>newsletter</strong></a> read by approximately 3000+ people across 89 countries and 47 states in the US.</p>

              <p style="margin-bottom: 1em;">The <a href="/archive" style="text-decoration: underline; color: #0066cc;"><strong>archive</strong></a> holds all the articles I've written, with <a href="/man-from-the-future" style="text-decoration: underline; color: #0066cc;"><strong>Man from the Future</strong></a> being the most interesting and popular one so far. On this blog, I track the books <a href="/library" style="text-decoration: underline; color: #0066cc;"><strong>I read</strong></a>, things <a href="/watch" style="text-decoration: underline; color: #0066cc;"><strong>I watch</strong></a>, things <a href="/dream" style="text-decoration: underline; color: #0066cc;"><strong>I want to do</strong></a>, projects <a href="/projects" style="text-decoration: underline; color: #0066cc;"><strong>I'm working on</strong></a>, and the stuff that <a href="/lifestack" style="text-decoration: underline; color: #0066cc;"><strong>I use</strong></a>.</p>

              <p style="margin-bottom: 1em;">To see what I'm currently up to, check out the <a href="/now" style="text-decoration: underline; color: #0066cc;"><strong>now</strong></a> page. For more about me, visit the <a href="/about" style="text-decoration: underline; color: #0066cc;"><strong>about</strong></a> page or <a href="/contact" style="text-decoration: underline; color: #0066cc;"><strong>say hi!</strong></a></p>

             


                                
  socialIcons:
    - name: twitter
      url: "https://twitter.com/rishikeshshari"
    - name: discord
      url:  "https://discord.gg/pkC6pngR"
    - name: github
      url: "https://github.com/rishikeshsreehari"
    - name: reddit
      url: "https://www.reddit.com/user/rishikeshshari/"
    - name: strava
      url: "https://www.strava.com/athletes/67526871/"
    - name: ycombinator
      url: "https://news.ycombinator.com/user?id=rishikeshs"
    - name: buymeacoffee
      url: "https://tracking.rishikeshs.com/nl-intro-coffee?utm_source=rishikeshs.com"
    - name: email
      url: "mailto:hello@rishikeshs.com"
    - name: paypal
      url: "https://paypal.me/RishikeshSHari?country.x=IN&locale.x=en_GB?utm_source=rishikeshs.com"


  analytics:
    google:
      #SiteVerificationTag: "XYZabc"
    bing:
      #SiteVerificationTag: "XYZabc"
    yandex:
      #SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
   # Text: "Suggest Changes" # edit text
    #appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 30
    - identifier: library
      name: Library
      url: /library/
      weight: 40
    - identifier: Now
      name: Now
      url: /now/
      weight: 50
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 60


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai


