name: Build and Deploy to Production

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Get last human commit short hash
      id: get_commit
      run: echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run build.py with last commit hash
      run: |
        python scripts/build.py  # Assuming build.py reads from GIT_COMMIT_HASH env variable
      env:
        GIT_COMMIT_HASH: ${{ env.commit_hash }}

    - name: Stage and commit changes before pulling
      run: |
        git add .
        git commit -m "Stash changes before pull" || echo "No changes to commit"

    - name: Pull latest changes before commit
      run: |
        git pull --rebase origin main

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automatic build by Github Actions" || echo "No changes to commit"
        git push origin main

    - name: Push to production branch
      run: |
        git checkout main
        git checkout -B production
        git push origin production --force
