name: Build and Deploy to Production

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run build.py
      env:
        TELEGRAPH_TOKEN: ${{ secrets.TELEGRAPH_TOKEN }}
        TINY_REDIRECTS_TOKEN: ${{ secrets.TINY_REDIRECTS_TOKEN }}
      run: |
        python scripts/build.py

    - name: Configure Git author
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Stage and commit changes before pulling
      run: |
        git add .
        git commit -m "Stash changes before pull" || echo "No changes to commit"

    - name: Pull latest changes before commit
      run: |
        git pull --rebase origin main

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Automatic build by Github Actions" || echo "No changes to commit"
        git push origin main